/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepComponent: typeof import('./src/components/StepComponent.vue')['default']
    StepperComponent: typeof import('./src/components/StepperComponent.vue')['default']
  }
}
